# Generated by Django 4.1.7 on 2023-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
