# Generated by Django 4.1.7 on 2023-09-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
