# Generated by Django 4.1.7 on 2023-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_live_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_chat',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
